version: "3"
services:
  api:
    build: ./api
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      PORT: 8000
    expose:
      - 8000
    ports:
      - '8081:8000'

  frontend-build:
    build: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      API_URL: https://api:8000
      PORT: 8000
    ports:
      - 8000:8000

  web:
    image: abiosoft/caddy
    volumes:
      - ./web/dist:/srv
    ports:
      - '8080:2015'
